import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import {
  faReact,
  faCss3Alt,
  faHtml5,
  faJs,
  faPhp,
  faSass,
} from "@fortawesome/free-brands-svg-icons"
import { faIndustry, faVial } from "@fortawesome/free-solid-svg-icons"

export const projects = [
  {
    name: "Oh My Food",
    id: "poniatowskijuliette_3_08022022",
    urlDemo: "https://popy49.github.io/poniatowskijuliette_3_08022022/",
    urlCode: "",
    urlPicture: "mock1.webp",
    progress: "",
    icons: [faHtml5, faCss3Alt, faSass],
  },
  {
    name: "Algorithme de recherche",
    id: "P7_algorithme_recherche",
    urlDemo: " https://popy49.github.io/P7_algorithme_recherche/",
    urlCode: "",
    urlPicture: "mock2.webp",
    progress: "",
    icons: [faHtml5, faCss3Alt, faSass, faJs],
  },
  {
    name: "Application de réservation",
    id: "P11_Kasa",
    urlDemo: " https://popy49.github.io/P11_Kasa/",
    urlCode: "",
    urlPicture: "mock3.webp",
    progress: "",
    icons: [faHtml5, faCss3Alt, faSass, faReact],
  },
  {
    name: "Jeux démineur",
    id: "Game_Demineur",
    urlDemo: " https://popy49.github.io/Game_Demineur/",
    urlCode: "",
    urlPicture: "mock4.webp",
    progress: "",
    icons: [faHtml5, faCss3Alt, faJs],
  },
  {
    name: "Booki",
    id: "P2_OCR_Booki_022022",
    urlDemo: " https://github.com/Popy49/P2_OCR_Booki_022022",
    urlCode: "",
    urlPicture: "mock5.webp",
    progress: "",
    icons: [faHtml5, faCss3Alt],
  },
  {
    name: "Photographers gallery",
    id: "Front-End-Fisheye",
    urlDemo: " https://github.com/Popy49/Front-End-Fisheye",
    urlCode: "",
    urlPicture: "mock6.webp",
    progress: "",
    icons: [faHtml5, faCss3Alt, faJs, faSass, faVial],
  },
  {
    name: "Testing and debbuging Saas application",
    id: "P9_Billed",
    urlDemo: "",
    urlCode: "",
    urlPicture: "mock7.webp",
    progress: "",
    icons: [faHtml5, faCss3Alt, faJs, faSass, faIndustry],
  },
  {
    name: "Website for a compagny",
    id: "",
    urlDemo: "https://auregestion.com/",
    urlCode: "https://auregestion.com/",
    urlPicture: "mock8.webp",
    progress: "",
    icons: [faHtml5, faCss3Alt, faJs, faPhp],
  },
]
